name: bb-actions-misc

on: 
  schedule:
    - cron:  '0 0 * * *'

env:
  TARGET: https://public-dns.info/nameservers-all.txt
  OUTPUT_FILE: outputs/resolvers.txt

jobs:
  resfresh-resolvers-list:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Checkout repo local repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install DNS Validator
        run: pip install git+https://github.com/vortexau/dnsvalidator.git

      - name: Generate new resolvers
        run: dnsvalidator -tL $TARGET -threads 200 --silent -o $OUTPUT_FILE

      - name: Set current date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git pull
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "its0x08"
          git add $OUTPUT_FILE
          git commit -m "${NOW} update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
