name: bb-actions-http

on:
  push:
    paths:
    - '.github/workflows/http-httpx.yml'

env:
  TARGET: outputs/masscan.txt
  OUTPUT_TEMP: outputs/httpx.txt
  OUTPUT_FILE: outputs/httpx-filtered.txt

jobs:
  http-httpx:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
      - run: go version
    
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install httpx
        run: go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

      - name: Run httpx against targets
        run: httpx -l $TARGET -o $OUTPUT_TEMP -threads 1000 -random-agent -title -td -nf

      - name: Filter output
        run: cut -d' ' -f 1 OUTPUT_TEMP > $OUTPUT_FILE

      - name: Set current date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git pull
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "its0x08"
          git add $OUTPUT_FILE
          git commit -m "${NOW} update"
    
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main