name: bb-actions-ports

on:
  push:
    paths:
    - '.github/workflows/portscan-masscan.yml'

jobs:
  ports-masscan:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt -y install git make gcc libpcap-dev

      - name: Clone Masscan repo
        run: git clone https://github.com/robertdavidgraham/masscan

      - name: Build and install Masscan
        run: |
          cd masscan
          make -j $(nproc)
          sudo make install
          make clean


      - name: Get CIDR list
        run: wget https://raw.githubusercontent.com/herrbischoff/country-ip-blocks/master/ipv4/al.cidr

      - name: Scan host
        run: sudo masscan -p 80 -iL al.cidr -oL /tmp/masscan.txt --rate=2048

      - name: Filter IPs
        run: grep open /tmp/masscan.txt|cut -d' ' -f 4 > outputs/masscan.txt

      - name: Set current date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git pull
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "its0x08"
          git add outputs/masscan.txt
          git commit -m "${NOW} update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main