name: bb-actions-ports

on:
  push:
    paths:
    - '.github/workflows/portscan-masscan.yml'

jobs:
  ports-masscan:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt -y install git make gcc libpcap-dev

      - name: Clone Masscan repo
        run: git clone https://github.com/robertdavidgraham/masscan

      - name: Build and install Masscan
        run: |
          cd masscan
          make -j $(nproc)
          sudo make install
          make clean


      - name: Get CIDR list
        run: wget https://raw.githubusercontent.com/herrbischoff/country-ip-blocks/master/ipv4/al.cidr

      - name: Scan host
        run: sudo masscan -p 80,81,300,443,591,593,832,981,1010,1311,2082,2087,2095,2096,2480,3000,3333,4243,4567,4711,4712,4993,5000,5104,5108,5800,6543,7000,7396,7474,8000,8001,8008,8014,8042,8069,8080,8081,8088,8090,8091,8118,8123,8172,8222,8243,8280,8281,8333,8443,8500,8834,8880,8888,8983,9000,9043,9060,9080,9090,9091,9200,9443,9800,9981,12443,16080,18091,18092,20720,28017 -iL al.cidr -oL /tmp/masscan.txt --rate=10240

      - name: Filter and sort IPs
        run: grep open /tmp/masscan.txt| awk '{print $4":"$3}' > outputs/masscan.txt

      - name: Set current date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git pull
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "its0x08"
          git add outputs/masscan.txt
          git commit -m "${NOW} update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main